// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingControl.Infra.Data.Context;

#nullable disable

namespace ParkingControl.Infra.Data.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20240921030304_MigrationAlteracaoTabelaTarifas")]
    partial class MigrationAlteracaoTabelaTarifas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParkingControl.Domain.Entities.Tarifa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataFimVigencia")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicioVigencia")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Preco")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Tarifas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataFimVigencia = new DateTime(2022, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicioVigencia = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 2.0
                        },
                        new
                        {
                            Id = 2,
                            DataFimVigencia = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicioVigencia = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 2.0
                        },
                        new
                        {
                            Id = 3,
                            DataFimVigencia = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicioVigencia = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 2.0
                        });
                });

            modelBuilder.Entity("ParkingControl.Domain.Entities.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataHoraEntrada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataHoraSaida")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Veiculos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataHoraEntrada = new DateTime(2023, 7, 4, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            DataHoraSaida = new DateTime(2023, 7, 4, 14, 10, 0, 0, DateTimeKind.Unspecified),
                            Placa = "MMD5544"
                        },
                        new
                        {
                            Id = 2,
                            DataHoraEntrada = new DateTime(2023, 7, 4, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            DataHoraSaida = new DateTime(2023, 7, 4, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            Placa = "DDM8474"
                        },
                        new
                        {
                            Id = 3,
                            DataHoraEntrada = new DateTime(2023, 7, 4, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            DataHoraSaida = new DateTime(2023, 7, 4, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Placa = "BRA2E23"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
